
import { HalalStatus, Product, Category } from './types.ts';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Все', icon: '🕋' },
  { id: 'dairy', name: 'Молочное', icon: '🥛' },
  { id: 'meat', name: 'Мясо', icon: '🥩' },
  { id: 'snacks', name: 'Снеки', icon: '🍿' },
  { id: 'sweets', name: 'Сладости', icon: '🍬' },
  { id: 'drinks', name: 'Напитки', icon: '🥤' },
  { id: 'e-numbers', name: 'E-добавки', icon: '🧪' },
  { id: 'sauces', name: 'Соусы', icon: '🥫' },
  { id: 'frozen', name: 'Заморозка', icon: '❄️' },
  { id: 'bakery', name: 'Выпечка', icon: '🍞' },
  { id: 'baby', name: 'Детское', icon: '👶' },
];

const boycottPepsi = "PepsiCo инвестирует в израильские стартапы и владеет акциями SodaStream, имеющей заводы на спорных территориях.";
const boycottNestle = "Nestle владеет 100% акций Osem, крупнейшего производителя продуктов в Израиле, и активно финансирует местную экономику.";
const boycottMondelez = "Mondelēz International (Oreo, Milka) спонсирует экономические проекты на территориях, признанных ООН оккупированными.";
const boycottMars = "Mars Inc поддерживает стратегическое партнерство с израильскими институтами в области продовольственных технологий.";
const boycottKellogg = "Kellogg's является крупным инвестором в израильские венчурные фонды и поддерживает государственные продовольственные программы.";
const boycottDanone = "Danone владеет долей в Strauss Group, которая известна своей прямой поддержкой военных подразделений Израиля.";
const boycottCocaCola = "Coca-Cola имеет заводы на территории поселений, что противоречит международному праву, и оказывает финансовую поддержку государству.";
const boycottUnilever = "Unilever долгое время владела Ben & Jerry's, продолжая продажи в поселениях вопреки этическим нормам, и инвестирует в израильские активы.";

export const INITIAL_PRODUCTS: Product[] = [
  // DAIRY (10+)
  { id: 'd1', name: 'Молоко Ак-Сут 2.5%', brand: 'Ак-Сут', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1550583724-125581cb284b?w=400', ingredients: ['Молоко'], explanation: 'Натуральное пастеризованное молоко местного производства.' },
  { id: 'd2', name: 'Кефир Ош-Сут 1%', brand: 'Ош-Сут', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1620189503995-133a8b948f6c?w=400', ingredients: ['Молоко', 'Закваска'], explanation: 'Чистый продукт ферментации.' },
  { id: 'd3', name: 'Йогурт Danone Клубника', brand: 'Danone', status: HalalStatus.MUSHBOOH, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=400', ingredients: ['Молоко', 'Желатин'], explanation: 'Содержит сомнительный желатин без сертификата Халяль.', isBoycotted: true, boycottReason: boycottDanone },
  { id: 'd4', name: 'Творог Веселый Молочник', brand: 'Вимм-Билль-Данн', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1559561853-08451507cbe7?w=400', ingredients: ['Творог'], explanation: 'Допустимо к употреблению.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 'd5', name: 'Сыр President Emmental', brand: 'President', status: HalalStatus.MUSHBOOH, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1485962391945-424503415cc2?w=400', ingredients: ['Сычужный фермент'], explanation: 'Фермент может быть не халяльным (животного происхождения).' },
  { id: 'd6', name: 'Молоко Савушкин 3.2%', brand: 'Савушкин', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1563636619-e910009355dc?w=400', ingredients: ['Молоко'], explanation: 'Проверено независимыми экспертами.' },
  { id: 'd7', name: 'Сметана Простоквашино', brand: 'Danone', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1584263347416-85a18a4524a3?w=400', ingredients: ['Сливки'], explanation: 'Состав чист.', isBoycotted: true, boycottReason: boycottDanone },
  { id: 'd8', name: 'Сливки Parmalat 10%', brand: 'Parmalat', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1596722505646-681b9e07802a?w=400', ingredients: ['Сливки'], explanation: 'Халяльный состав.' },
  { id: 'd9', name: 'Йогурт Bio-Max', brand: 'PepsiCo', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1563636619-e910009355dc?w=400', ingredients: ['Молоко'], explanation: 'Ингредиенты разрешены.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 'd10', name: 'Ряженка Домик в деревне', brand: 'Вимм-Билль-Данн', status: HalalStatus.HALAL, category: 'dairy', imageUrl: 'https://images.unsplash.com/photo-1550583724-125581cb284b?w=400', ingredients: ['Молоко'], explanation: 'Традиционное топленое молоко.', isBoycotted: true, boycottReason: boycottPepsi },

  // MEAT (10+)
  { id: 'm1', name: 'Говядина Филе', brand: 'Ош-Базар', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400', ingredients: ['Говядина'], explanation: 'Местный халяльный убой.' },
  { id: 'm2', name: 'Колбаса Тойбосс Докторская', brand: 'Тойбосс', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400', ingredients: ['Говядина'], explanation: 'Сертификат Халяль КР.' },
  { id: 'm3', name: 'Сосиски Адал', brand: 'Риха', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400', ingredients: ['Птица'], explanation: 'Разрешено официально.' },
  { id: 'm4', name: 'Цыпленок Ак-Куу', brand: 'Ак-Куу', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1587593817645-4250404a5161?w=400', ingredients: ['Курица'], explanation: 'Птица убоя по шариату.' },
  { id: 'm5', name: 'Мясо Индейки', brand: 'Элдик', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400', ingredients: ['Индейка'], explanation: 'Халяльное мясо.' },
  { id: 'm6', name: 'Говяжья Тушенка', brand: 'Узген', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400', ingredients: ['Говядина'], explanation: 'Чистая консервация.' },
  { id: 'm7', name: 'Пельмени Мясные', brand: 'Ош-Мясо', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400', ingredients: ['Говядина'], explanation: 'Местная ручная лепка.' },
  { id: 'm8', name: 'Фарш Бараний', brand: 'Базар', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400', ingredients: ['Баранина'], explanation: 'Свежий убой.' },
  { id: 'm9', name: 'Колбаса Сервелат', brand: 'Тойбосс', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400', ingredients: ['Говядина'], explanation: 'Халяль продукт.' },
  { id: 'm10', name: 'Котлеты для бургера', brand: 'Meat Point', status: HalalStatus.HALAL, category: 'meat', imageUrl: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400', ingredients: ['Мясо'], explanation: '100% Халяль.' },

  // SNACKS (10+)
  { id: 's1', name: 'Lay\'s Сметана и Лук', brand: 'Lay\'s', status: HalalStatus.MUSHBOOH, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400', ingredients: ['Сыворотка'], explanation: 'Содержит сыворотку сомнительного происхождения.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 's2', name: 'Pringles Original', brand: 'Kellogg\'s', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', ingredients: ['Картофель'], explanation: 'Чистый растительный состав.', isBoycotted: true, boycottReason: boycottKellogg },
  { id: 's3', name: 'Cheetos Ketchup', brand: 'PepsiCo', status: HalalStatus.HARAM, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1600952841320-db92ec4047ca?w=400', ingredients: ['Сычужный фермент'], explanation: 'Содержит не халяльный сырный порошок.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 's4', name: 'Doritos Nacho Cheese', brand: 'PepsiCo', status: HalalStatus.MUSHBOOH, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1600952841320-db92ec4047ca?w=400', ingredients: ['Сырный порошок'], explanation: 'Происхождение ферментов сыра не подтверждено.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 's5', name: 'Tuc Original', brand: 'Mondelez', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', ingredients: ['Мука'], explanation: 'Состав допустим.', isBoycotted: true, boycottReason: boycottMondelez },
  { id: 's6', name: 'Kracks Original', brand: 'Food Empire', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', ingredients: ['Картофель'], explanation: 'Растительный состав.' },
  { id: 's7', name: 'Lorenz Pomsticks', brand: 'Lorenz', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', ingredients: ['Картофель'], explanation: 'Халяль.' },
  { id: 's8', name: 'Курут Ошский', brand: 'Домашний', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1620189503995-133a8b948f6c?w=400', ingredients: ['Молоко'], explanation: 'Народный продукт.' },
  { id: 's9', name: 'Семечки Джинн', brand: 'Smart', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', ingredients: ['Семена'], explanation: 'Растительно.' },
  { id: 's10', name: 'Bingo Чипсы', brand: 'Bingo', status: HalalStatus.HALAL, category: 'snacks', imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', ingredients: ['Картофель'], explanation: 'Халяль.' },

  // SWEETS (10+)
  { id: 'sw1', name: 'Oreo Original', brand: 'Mondelez', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', ingredients: ['Какао'], explanation: 'Не содержит животных жиров.', isBoycotted: true, boycottReason: boycottMondelez },
  { id: 'sw2', name: 'Snickers', brand: 'Mars', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=400', ingredients: ['Арахис'], explanation: 'Состав разрешен.', isBoycotted: true, boycottReason: boycottMars },
  { id: 'sw3', name: 'Haribo Classic (DE)', brand: 'Haribo', status: HalalStatus.HARAM, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400', ingredients: ['Свиной желатин'], explanation: 'Содержит свиной желатин.' },
  { id: 'sw4', name: 'Alpen Gold', brand: 'Mondelez', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?w=400', ingredients: ['Молоко'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottMondelez },
  { id: 'sw5', name: 'Mars Bar', brand: 'Mars', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=400', ingredients: ['Карамель'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottMars },
  { id: 'sw6', name: 'Twix', brand: 'Mars', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=400', ingredients: ['Печенье'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottMars },
  { id: 'sw7', name: 'Milka', brand: 'Mondelez', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottMondelez },
  { id: 'sw8', name: 'Bounty', brand: 'Mars', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=400', ingredients: ['Кокос'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottMars },
  { id: 'sw9', name: 'Kinder Surprise', brand: 'Ferrero', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?w=400', ingredients: ['Молоко'], explanation: 'Разрешено.' },
  { id: 'sw10', name: 'Рахат Шоколад', brand: 'Рахат', status: HalalStatus.HALAL, category: 'sweets', imageUrl: 'https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?w=400', ingredients: ['Какао'], explanation: 'Халяль сертификат Казахстана.' },

  // DRINKS (10+)
  { id: 'dr1', name: 'Coca-Cola Zero', brand: 'Coca-Cola', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400', ingredients: ['Заменители сахара'], explanation: 'Без алкоголя и сомнительных компонентов.', isBoycotted: true, boycottReason: boycottCocaCola },
  { id: 'dr2', name: 'Pepsi', brand: 'PepsiCo', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400', ingredients: ['Сахар'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 'dr3', name: 'Red Bull', brand: 'Red Bull', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400', ingredients: ['Таурин'], explanation: 'Таурин имеет синтетическое происхождение.' },
  { id: 'dr4', name: 'Monster Energy', brand: 'Monster', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400', ingredients: ['Витамины'], explanation: 'Халяль.' },
  { id: 'dr5', name: 'Fanta Orange', brand: 'Coca-Cola', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400', ingredients: ['Апельсин'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottCocaCola },
  { id: 'dr6', name: 'Sprite', brand: 'Coca-Cola', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400', ingredients: ['Лимон'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottCocaCola },
  { id: 'dr7', name: 'Nescafe', brand: 'Nestle', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Кофе'], explanation: 'Растительно.', isBoycotted: true, boycottReason: boycottNestle },
  { id: 'dr8', name: 'Lipton Ice Tea', brand: 'Unilever', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Чай'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottUnilever },
  { id: 'dr9', name: 'Rich Juice', brand: 'Multon', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Фрукты'], explanation: 'Натурально.', isBoycotted: true, boycottReason: boycottCocaCola },
  { id: 'dr10', name: 'Maxi Tea', brand: 'RG Brands', status: HalalStatus.HALAL, category: 'drinks', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Чай'], explanation: 'Халяль.' },

  // E-NUMBERS (10+)
  { id: 'e120', name: 'E120 Кармин', brand: 'Краситель', status: HalalStatus.HARAM, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=400', ingredients: ['Насекомые'], explanation: 'Красный краситель из кошенили. Харам.' },
  { id: 'e441', name: 'E441 Желатин', brand: 'Добавка', status: HalalStatus.MUSHBOOH, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400', ingredients: ['Животные'], explanation: 'Часто свиной. Сомнительно без сертификата.' },
  { id: 'e471', name: 'E471 Эмульгатор', brand: 'Добавка', status: HalalStatus.MUSHBOOH, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1628113315911-d19ca72f99de?w=400', ingredients: ['Жиры'], explanation: 'Может быть животного происхождения.' },
  { id: 'e904', name: 'E904 Шеллак', brand: 'Добавка', status: HalalStatus.MUSHBOOH, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1628113315911-d19ca72f99de?w=400', ingredients: ['Насекомые'], explanation: 'Выделения насекомых. Спорно.' },
  { id: 'e100', name: 'E100 Куркумин', brand: 'Добавка', status: HalalStatus.HALAL, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=400', ingredients: ['Растение'], explanation: 'Растительный краситель.' },
  { id: 'e150', name: 'E150 Карамель', brand: 'Добавка', status: HalalStatus.HALAL, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=400', ingredients: ['Сахар'], explanation: 'Безопасно.' },
  { id: 'e202', name: 'E202 Сорбат калия', brand: 'Добавка', status: HalalStatus.HALAL, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=400', ingredients: ['Химия'], explanation: 'Синтетический консервант.' },
  { id: 'e211', name: 'E211 Бензоат натрия', brand: 'Добавка', status: HalalStatus.HALAL, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=400', ingredients: ['Химия'], explanation: 'Разрешено.' },
  { id: 'e322', name: 'E322 Лецитин', brand: 'Добавка', status: HalalStatus.HALAL, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1628113315911-d19ca72f99de?w=400', ingredients: ['Соя'], explanation: 'Обычно растительный.' },
  { id: 'e951', name: 'E951 Аспартам', brand: 'Добавка', status: HalalStatus.HALAL, category: 'e-numbers', imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=400', ingredients: ['Химия'], explanation: 'Разрешено.' },

  // SAUCES (10+)
  { id: 'sau1', name: 'Кетчуп Heinz', brand: 'Heinz', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Томаты'], explanation: 'Растительно.', isBoycotted: true, boycottReason: "Входит в списки из-за сложной структуры собственности и связей." },
  { id: 'sau2', name: 'Майонез Слобода', brand: 'Эфко', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Яйца'], explanation: 'Натурально.' },
  { id: 'sau3', name: 'Maggi Бульон', brand: 'Nestle', status: HalalStatus.MUSHBOOH, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Животные жиры'], explanation: 'Происхождение жира не уточнено.', isBoycotted: true, boycottReason: boycottNestle },
  { id: 'sau4', name: 'Tabasco Sauce', brand: 'Tabasco', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Перец'], explanation: 'Халяль.' },
  { id: 'sau5', name: 'Hellmann\'s', brand: 'Unilever', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Масло'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottUnilever },
  { id: 'sau6', name: 'Knorr Dressing', brand: 'Unilever', status: HalalStatus.MUSHBOOH, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Добавки'], explanation: 'Требует проверки.', isBoycotted: true, boycottReason: boycottUnilever },
  { id: 'sau7', name: 'Соус Чили', brand: 'Ош', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Перец'], explanation: 'Халяль.' },
  { id: 'sau8', name: 'Kikkoman Soy', brand: 'Kikkoman', status: HalalStatus.MUSHBOOH, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Спирт'], explanation: 'Может содержать алкоголь естественного брожения.' },
  { id: 'sau9', name: 'Calve Ketchup', brand: 'Unilever', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Томаты'], explanation: 'Допустимо.', isBoycotted: true, boycottReason: boycottUnilever },
  { id: 'sau10', name: 'Соус Терияки', brand: 'Generic', status: HalalStatus.HALAL, category: 'sauces', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Соя'], explanation: 'Халяль.' },

  // FROZEN (10+)
  { id: 'fz1', name: 'Манты Говяжьи', brand: 'Тойбосс', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мясо'], explanation: 'Халяль.' },
  { id: 'fz2', name: 'Картофель McCain', brand: 'McCain', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Картофель'], explanation: 'Халяль.' },
  { id: 'fz3', name: 'Пицца Ristorante', brand: 'Dr. Oetker', status: HalalStatus.MUSHBOOH, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Сыр'], explanation: 'Сычужный фермент.' },
  { id: 'fz4', name: 'Мороженое Mars', brand: 'Mars', status: HalalStatus.MUSHBOOH, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Желатин'], explanation: 'Проверка эмульгаторов.', isBoycotted: true, boycottReason: boycottMars },
  { id: 'fz5', name: 'Овощная Смесь', brand: 'Hortex', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Овощи'], explanation: 'Растительно.' },
  { id: 'fz6', name: 'Вишня', brand: 'Местная', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Вишня'], explanation: 'Халяль.' },
  { id: 'fz7', name: 'Рыбные Палочки', brand: 'Generic', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Рыба'], explanation: 'Халяль.' },
  { id: 'fz8', name: 'Пельмени Халяль', brand: 'Ош', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мясо'], explanation: 'Халяль.' },
  { id: 'fz9', name: 'Креветки', brand: 'Ocean', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Морепродукты'], explanation: 'Халяль.' },
  { id: 'fz10', name: 'Тесто Слоеное', brand: 'Местное', status: HalalStatus.HALAL, category: 'frozen', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.' },

  // BAKERY (10+)
  { id: 'bk1', name: 'Лепешка', brand: 'Тандыр', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.' },
  { id: 'bk2', name: 'Хлеб Нарезной', brand: 'Ош-Нан', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.' },
  { id: 'bk3', name: '7Days Croissant', brand: 'Chipita', status: HalalStatus.MUSHBOOH, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Эмульгаторы'], explanation: 'Требует проверки.' },
  { id: 'bk4', name: 'Юбилейное', brand: 'Mondelez', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottMondelez },
  { id: 'bk5', name: 'Торт Медовик', brand: 'Куликовский', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мед'], explanation: 'Халяль.' },
  { id: 'bk6', name: 'Лаваш', brand: 'Местный', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.' },
  { id: 'bk7', name: 'Багет', brand: 'Bakery', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.' },
  { id: 'bk8', name: 'Сухарики', brand: 'Местные', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Хлеб'], explanation: 'Халяль.' },
  { id: 'bk9', name: 'Булочка', brand: 'Bakery', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мука'], explanation: 'Халяль.' },
  { id: 'bk10', name: 'Самсы', brand: 'Тандыр', status: HalalStatus.HALAL, category: 'bakery', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400', ingredients: ['Мясо'], explanation: 'Халяль.' },

  // BABY (10+)
  { id: 'bb1', name: 'Gerber Apple', brand: 'Nestle', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Яблоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottNestle },
  { id: 'bb2', name: 'Heinz Porridge', brand: 'Heinz', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Злаки'], explanation: 'Халяль.', isBoycotted: true, boycottReason: "Heinz." },
  { id: 'bb3', name: 'Hipp Veggie', brand: 'Hipp', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Овощи'], explanation: 'Халяль.' },
  { id: 'bb4', name: 'Агуша', brand: 'PepsiCo', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottPepsi },
  { id: 'bb5', name: 'ФрутоНяня', brand: 'Прогресс', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Фрукты'], explanation: 'Халяль.' },
  { id: 'bb6', name: 'Nestogen', brand: 'Nestle', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottNestle },
  { id: 'bb7', name: 'Малютка', brand: 'Danone', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottDanone },
  { id: 'bb8', name: 'Nan', brand: 'Nestle', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottNestle },
  { id: 'bb9', name: 'Тема', brand: 'Danone', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottDanone },
  { id: 'bb10', name: 'Nutrilon', brand: 'Danone', status: HalalStatus.HALAL, category: 'baby', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', ingredients: ['Молоко'], explanation: 'Халяль.', isBoycotted: true, boycottReason: boycottDanone },
];
